
name: Run automated E2E Testing
on:
  pull_request:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Run Cypress test using Electron
        uses: cypress-io/github-action@v4
        with:
          browser: electron
