name: Run Automated Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under /$GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'  

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
